server:
  port: 8080

logging:
  level:
    root: INFO
  pattern:
    correlation: "[ %X{userId:-}, %X{ traceId:- }, %X{ spanId:- } ]"
  include-application-name: false

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  tracing:
    sampling:
      probability: 1
    baggage:
      correlation:
        fields:
          - userId # Propagates the baggage to the MDC
  #      remote-fields:
  #        - userId Propagates baggage over the network if B3 propagation is used. If W3C propagation is used, then this is not needed.
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans