networks:
  backend:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  user-service:
    image: user-service:latest
    build:
      context: ./user-service
    networks:
      - backend

  product-service:
    image: product-service:latest
    build:
      context: ./product-service
    networks:
      - backend

  order-service:
    image: order-service:latest
    build:
      context: ./order-service
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:8080
      - PRODUCT_SERVICE_URL=http://product-service:8080
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - backend

  notification-service:
    image: notification-service:latest
    build:
      context: ./notification-service
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - backend
