server:
  port: 8080

logging:
  level:
    root: DEBUG

spring:
  application:
    name: user-service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
