server:
  port: 8080

spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

external:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8082}
