server:
  port: 8080

spring:
  application:
    name: order-service

external:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8082}
