server:
  port: 8080

logging:
  level:
    root: INFO
  pattern:
    correlation: "[ %X{userId:-}, %X{ traceId:- }, %X{ spanId:- } ]"
  include-application-name: false

spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

external:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  product-service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8082}

management:
  tracing:
    sampling:
      probability: 1
    baggage:
      correlation:
        fields:
          - userId # Propagates the baggage to the MDC
  #      remote-fields:
  #        - userId Propagates baggage over the network if B3 propagation is used. If W3C propagation is used, then this is not needed.
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
